analyze_drug_patient_interaction_task:
  description: >
    Analyze the interaction between the given patient information :{patient_info}, and the prescribed drug list:{drug_list}.
    Identify any potential conflicts and provide feedback. If there is a conflict, suggest the most suitable alternative drug.
  expected_output: >
    1. Tell me whether there are conflicts or not.
    2. If there is a conflict between the patient information and the drug, analysis the reason for the conflict (if any), and recommend the most suitable alternative drug and the reasons(if applicable).
    3. If you recommend an alternative drug, please provide the final drug list for the patient.
  agent: drug_patient_interaction_analyzer
  output_file: output/drug_patient_interaction.json