patient_info_cleaner_task:
  description: >
    Given a patient statement: {statement}, convert the statement into a list of the patient's
    conditions, including name, age, gender, weight(cm), height(kg), bad habits, symptom, and
    other information.
  expected_output: >
    A list of the patient's conditions, including name, age,gender, weight(cm),
    height(kg), symptom, and other information.
  agent: patient_info_cleaner
  output_file: output/drug_info.json
