# patient_info_cleaner_task:
#   description: >
#      Provide a free text clinical note of a patient, which is a txt file.
#      You need to convert this free texts into different structured parts, extract the accurate and full information that mentioned in the txt file, you can not omit any information.
#      YOU CAN NOT use '...' to omit any information, I need the full txt contents.
#      You can use txt_search_tool to get the content of the txt files.
#      Here is the list of categories, Find the corresponding txt files one by one in sequence and extract the complete information from them.
#       1. Patient_Demographics
#       2. Chief_Complaint
#       3. Allergies
#       4. History_of_Present_Illness
#       5. Past_Medical_History
#       6. Social_history_and_family_history
#       7. Physical_Exam
#       8. Medications_on_Admissions
#       9. Discharge_Diagnose
#       10. Discharge_Medications
#       11. Other_Discharge_Information

#   expected_output: >
#       Patient_Demographics: list[str]
#       Chief_Complaint: str
#       Allergies: list[str]
#       History_of_Present_Illness: list[str]
#       Past_Medical_History: list[str]
#       Social_history_and_family_history: list[str]
#       Physical_Exam: list[str]
#       Medications_on_Admissions: list[str]
#       Discharge_Diagnose: list[str]
#       Discharge_Medications: list[str]
#       Other_Discharge_Information: list[str]
# #   agent: patient_info_cleaner
#   output_file: output/drug_info.json

Medications_on_Admissions_Find_Task:
  description: >
    Given a text about the patient, Please find the content of the following contents in the text.
    You have to find it one by one. YOU CAN NOT use '...' to omit any information, I need the full txt contents.
    Topic List:
      Chief_Complaint
      Allergies
      History_of_Present_Illness
      Past_Medical_History
      Social_history
      Family_history
      Physical_Exam
      Medications_on_Admissions
      Discharge_Diagnose
      Discharge_Medications
      Other_Discharge_Information

    Here is the text: {text}.
  expected_output: >
      Chief_Complaint: str
      Allergies: list[str]
      History_of_Present_Illness: list[str]
      Past_Medical_History: list[str]
      Social_history: list[str]
      Family_history: list[str]
      Physical_Exam: list[str]
      Medications_on_Admissions: list[str]
      Discharge_Diagnose: list[str]
      Discharge_Medications: list[str]
      Other_Discharge_Information: list[str]
  agent: Medications_on_Admissions_finder
  output_file: output/info.json